### ISSUE TITLE
'CE' Button Error

### ISSUE THREAD

**Issue by jharsh1202** [jude-joy/Android-Calculator#1]
Once you print the result for any operation pressing the '=' button, then pressing CE button won't delete the contents of the numerical text view.

**Comment by jude-joy** [comment]
Thanks for reporting. I don't have Android Studio right now but I will try to resolve the problem this week.

**Comment by jharsh1202** [comment]
That's great, Though, I have fixed that bug, I will create a pull request soon.

**Comment by jharsh1202** [comment]
I have created a pull request for the fix.

**Comment by jharsh1202** [comment]
I have made the changes, you just have to accept the pull request, it won't
take any time.
